### ISSUE TITLE
npm module broken from version 7.1.0

### ISSUE THREAD

**Issue by giautm** [callstack-io/react-native-fbads#354]
# Bug Report

**Before opening**

- [x] Did you try the latest release?
- [x] Did you look for existing issues?

**Versions**

- react-native-fbads: 7.1.0

**Current Behaviour**

Bundle error due to missing "dist" directory.

**Expected Behaviour**

Able to install and use the module

**Steps to Reproduce**

**Additionals**

cc @thymikee: because you release the latest version here. and it doesn't include the "dist" directory in the npm module. You can check by download the gz from npm. The missing dist cause build error and no one can use this module.

**Comment by zuberqureshi** [comment]
correct

**Comment by zuberqureshi** [comment]
i am also facing the same issue

**Comment by zuberqureshi** [comment]
How could we solve this issue bro , Any idea ?

**Comment by matt-oakes** [comment]
This is something that can only be fixed by a new release. @thymikee Are you able to make a new patch release which includes the `dist` directory?

**Comment by thymikee** [comment]
@matt-oakes I used a different command now that outputs `dist` dir and published as 7.1.1. Please check if that works for you.

Btw, I really don't know what to do with this package. It's not actively maintained and seems not to be used by almost anyone. For interacting with FB SDK there's this though: https://github.com/thebergamo/react-native-fbsdk-next 

I consider archiving it. Would appreciate any advice from existing users and whether `react-native-fbsdk-next` is a valid alternative (which I believe is, but haven't checked empirically)

**Comment by matt-oakes** [comment]
@thymikee Thank you. The new version works great.

Unfortunatly, `react-native-fbsdk-next` does not cover the same usecase as `react-native-fbads` and it likely shouldn't. 

`fbsdk-next` is simply a wrapper around the Facebook SDK for [Android](https://developers.facebook.com/docs/android/) and [iOS](https://developers.facebook.com/docs/ios/). This SDK provides Facebook login, sharing to Facebook, and App Events for analytics and install tracking. The last part is used to track how effective adverts you place on Facebook are at driving traffic into your app.

`fbads` is instead a wrapper around the [Audience Network](https://developers.facebook.com/docs/audience-network/) SDK. This is for placing adverts inside your app to monitize it.

The libraries have different focuses and it would not be desireable to combine them. This is because if you include the Audience Network SDK in your app you need to declare it in your privacy policy and the app store listing. For most people who use `fbsdk-next`, they just don't need this additional SDK.

I understand that maintaining this requires some work, but as the SDK is fairly small and stable, it would be good if the library could be kept unarchived. If you do decide you don't want to keep it going, it would be good to transfer ownership to someone else to avoid the library on NPM becoming a deadend, like happend when Facebook abandoned `react-native-fbsdk` which required everyone realising it was unmaintained and moving to `react-native-fbsdk-next`.

**Comment by thymikee** [comment]
Thanks for the clarification. For now I'm good with keeping it running. I can do the releases, but no capacity for actual maintenance
