### ISSUE TITLE
error with didFailWithError

### ISSUE THREAD

**Issue by michaelspeed** [callstack-io/react-native-fbads#65]
i am getting this error for most of the time, it works mostly though - 

![screenshot at jul 04 02-46-37](https://user-images.githubusercontent.com/1447958/27808118-5d445372-6063-11e7-9d3b-e907f8adee90.png)

any thoughts how we could fix this?

**Comment by grabbou** [comment]
I will try to reproduce this issue - can you share how do you use it on the Javascript side? If I remember, this could happen as soon as either component is unmounted or the event has already been called.

**Comment by grabbou** [comment]
The issue happens because `NativeAdView` doesn't set `onAdError` prop -> https://github.com/callstack-io/react-native-fbads/blob/master/src/withNativeAd.js#L71

I believe we can fix it by setting it to `this.props.onAdError`, so that whoever renders `withNativeAd` wrapped component, can set that prop to listen to errors.

Handling itself is handled within that wrapper anyway (in case of error - `nativeAd` is null and nothing is rendered).

**Comment by grabbou** [comment]
You need to provide required `onError` prop for `BannerView`. Otherwise, when error occurs, your native code will throw.
